### ISSUE TITLE
auto refresh on dashboard not working on new release

### ISSUE THREAD

**Issue by scooper1** [hassio-addons/addon-appdaemon#44]
# Problem/Motivation

after upgrade to version 3.0 The dashboard does not update on fully kiosk browser 
the screen is drawn ok but values do  not update - doing a full page refresh works ok 
works ok from a chrome browser on  desktop and Andriod

## Expected behavior

values to update when changed on the server

## Actual behavior
all screen values are static except the digital clock
no errors are shown in the log

**Comment by frenck** [comment]
Please report this issue with the AppDaemon project. From an add-on perspective, this is not addressable.

Thanks 👍
